### ISSUE TITLE
dcrlibwallet: Update it.

### ISSUE THREAD

**Issue by JoeGruffins** [JoeGruffins/cake_wallet#3]
The library will not be part of this repo. Just leaving this here as a milestone to be closed at some point. The dcrlibwallet is the one that is currently inside https://github.com/crypto-power/cryptopower . Current plan is for it to be moved to a new repo and used by both projects.

**Comment by xaur** [comment]
Do not confuse the older [dcrlibwallet](https://github.com/planetdecred/dcrlibwallet) (it was used for GoDCR, dcrandroid, dcrios) and the newer [libwallet](https://github.com/crypto-power/cryptopower/tree/master/libwallet) directory in the Cryptopower repo. I'm not sure if libwallet is a package or a module.

Then there's the newest [libwallet repository](https://github.com/itswisdomagain/libwallet) in the works.

**Comment by JoeGruffins** [comment]
> Then there's the newest [libwallet repository](https://github.com/itswisdomagain/libwallet) in the works.

This is the one this project is funding. Hoping to get it under the decred org repo eventually.

**Comment by JoeGruffins** [comment]
I guess this is done
